### ISSUE TITLE
评测函数有问题

### ISSUE THREAD

**Issue by MichelleYang2017** [JasonZhang156/Sound-Recognition-Tutorial#1]
keras里面的评测的ACC本质上计算是这样的：label：[[0,1,0,0],[0,0,0,1]]，pred:[[0,0,0,0],[0,0,0,1]]准确率不是50%,而是87.5%

**Comment by JasonZhang156** [comment]
keras使用‘accuracy’作为metrics时，默认调用的是[metrics.py](https://github.com/keras-team/keras/blob/c2e36f369b411ad1d0a40ac096fe35f73b9dffd3/keras/metrics.py)里的categorical_accuracy函数，如下
`def categorical_accuracy(y_true, y_pred):
    '''Calculates the mean accuracy rate across all predictions for
    multiclass classification problems.
    '''
    return K.mean(K.equal(K.argmax(y_true, axis=-1),
                  K.argmax(y_pred, axis=-1)))`

我认为计算方法是没有问题。

**Comment by MichelleYang2017** [comment]
eras使用‘accuracy’作为metrics时，默认调用的是metrics.py里的accuracy(y_true, y_pred)函数吧，当指定为metrics.categorical_accuracy才用的是categorical_accuracy函数吧

**Comment by JasonZhang156** [comment]
默认调用categorical_accuracy，可以参考[training.py](https://github.com/fchollet/keras/blob/d8b226f26b35348d934edb1213061993e7e5a1fa/keras/engine/training.py#L651)

**Comment by MichelleYang2017** [comment]
ok，感谢

z小白 <notifications@github.com> 于2019年12月5日周四 下午6:23写道：
